### ISSUE TITLE
not updated anymore ? any reasons ?

### ISSUE THREAD

**Issue by xieyuheng** [fukamachi/clozure-cl#1]

**Comment by fukamachi** [comment]
Just because the cron process is dead and I'm not interested in this anymore.

**Comment by xieyuheng** [comment]
so, what implementation are you using now ? SBCL instead of CCL ? or CL21 ?

**Comment by fukamachi** [comment]
I'm using SBCL mainly and sometimes using CCL.

What I meant is I'm not interested in following the development of CCL.
